services:
  mysql:
    container_name: mysql8_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: baitap3
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql8_container
      PMA_PORT: 3306
    ports:
      - "8081:80"
